[project]
name = "learn-lang"
version = "0.3.0a0"
description = "A tool used to help improve vocab and reading comprehension"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets~=5.0.1",
    "fastparquet>=2025.12.0",
    "pydantic~=2.13.4",
    "ruff>=0.15.2",
    "sentence-transformers>=5.6.1",
    "sqlalchemy>=2.0.51",
]

[tool.ruff]
line-length=100
lint.select = [
    "E", # pycodestyle errors
    "F", # pyflakes errors
    "I", # import-related checks
    "C", # cyclomatic complexity & code style
    "B", # flake8-bugbear style checks
    "D", # documentation
]
lint.ignore = [
    "D400",
    "D107",
    "D203", # conflicting w/ D211
    "D213", # conflicting w/ D212
    "D415",
    "D100" # should probably remove this later
]
target-version = "py314"
exclude = ["__pycache__", ".venv", "build", "dist"]


[tool.coverage.report]
skip_empty = true
sort = "cover"
skip_covered = true
fail_under = 0
exclude_also = [
    'if __name__ == .__main__.:',
]

[dependency-groups]
dev = [
    "coverage>=7.15.2",
]
